// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{GUEST_CODE_FOR_ZK_PROOF_ELF, GUEST_CODE_FOR_ZK_PROOF_ID};
use neuron_core::{NeuronInput, NeuronOutput, UserRecord};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserDiscord {
    pub id: String,
    pub tier: i32,
    pub username: Option<String>,
    pub discord_roles: Vec<String>,
    pub rounds_votes: Vec<u32>,
    pub rounds_public_keys: Option<HashMap<String, String>>,
}

/// Map of Stellar public key -> Discord user data.
pub type UsersDiscord = HashMap<String, UserDiscord>;

fn read_users_discord(path: impl AsRef<Path>) -> UsersDiscord {
    let raw = std::fs::read_to_string(path).expect("failed to read usersDiscord.json");
    serde_json::from_str(&raw).expect("failed to parse usersDiscord.json")
}

fn build_neuron_input(users: &UsersDiscord) -> NeuronInput {
    let mut records: Vec<UserRecord> = users
        .iter()
        .map(|(public_key, user)| UserRecord {
            public_key: public_key.clone(),
            tier: user.tier,
            discord_roles: user.discord_roles.clone(),
        })
        .collect();
    // Sort for a deterministic input (HashMap iteration order is random),
    // so the same data always produces the same journal.
    records.sort_by(|a, b| a.public_key.cmp(&b.public_key));
    NeuronInput { users: records }
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // Resolve the data file relative to this crate so it works from any cwd.
    let data_path = concat!(env!("CARGO_MANIFEST_DIR"), "/../data/usersDiscord.json");
    let users = read_users_discord(data_path);
    println!("Loaded {} users from usersDiscord.json", users.len());

    let input = build_neuron_input(&users);

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();
    let prove_info = prover.prove(env, GUEST_CODE_FOR_ZK_PROOF_ELF).unwrap();
    let receipt = prove_info.receipt;

    // The journal holds the proven neuron output.
    let output: NeuronOutput = receipt.journal.decode().unwrap();
    println!("Proved reputation scores for {} users", output.scores.len());
    for (public_key, bonus) in output.scores.iter().filter(|(_, b)| *b > 0.0).take(10) {
        println!("  {public_key} -> {bonus}");
    }

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(GUEST_CODE_FOR_ZK_PROOF_ID).unwrap();
    println!("Receipt verified.");
}
